/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReceiveRouteImport } from './routes/receive'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DocsIndexRouteImport } from './routes/docs/index'
import { Route as DocsCliRouteImport } from './routes/docs/cli'
import { Route as DocsApiRouteImport } from './routes/docs/api'
import { Route as DSlugRouteImport } from './routes/d/$slug'
import { Route as CliInstallDotshRouteImport } from './routes/cli/install[.]sh'
import { Route as CliFileshareDotshRouteImport } from './routes/cli/fileshare[.]sh'
import { Route as ApiUploadRouteImport } from './routes/api/upload'
import { Route as AuthenticatedKeysRouteImport } from './routes/_authenticated/keys'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as ApiUploadsIndexRouteImport } from './routes/api/uploads/index'
import { Route as ApiFilesSlugRouteImport } from './routes/api/files/$slug'
import { Route as ApiCliConfigRouteImport } from './routes/api/cli/config'
import { Route as ApiUploadsIdCompleteRouteImport } from './routes/api/uploads/$id.complete'
import { Route as ApiPublicV1QrRouteImport } from './routes/api/public/v1/qr'
import { Route as ApiPublicCronCleanupRouteImport } from './routes/api/public/cron/cleanup'
import { Route as ApiPublicV1UploadsInitRouteImport } from './routes/api/public/v1/uploads/init'
import { Route as ApiPublicV1MeKeysRouteImport } from './routes/api/public/v1/me/keys'
import { Route as ApiPublicV1MeDropsRouteImport } from './routes/api/public/v1/me/drops'
import { Route as ApiPublicV1DropsSlugRouteImport } from './routes/api/public/v1/drops/$slug'
import { Route as ApiPublicV1ClaimsCodeRouteImport } from './routes/api/public/v1/claims/$code'
import { Route as ApiPublicV1UploadsIdCompleteRouteImport } from './routes/api/public/v1/uploads/$id.complete'
import { Route as ApiPublicV1MeKeysIdRouteImport } from './routes/api/public/v1/me/keys.$id'

const ReceiveRoute = ReceiveRouteImport.update({
  id: '/receive',
  path: '/receive',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsIndexRoute = DocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsCliRoute = DocsCliRouteImport.update({
  id: '/docs/cli',
  path: '/docs/cli',
  getParentRoute: () => rootRouteImport,
} as any)
const DocsApiRoute = DocsApiRouteImport.update({
  id: '/docs/api',
  path: '/docs/api',
  getParentRoute: () => rootRouteImport,
} as any)
const DSlugRoute = DSlugRouteImport.update({
  id: '/d/$slug',
  path: '/d/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const CliInstallDotshRoute = CliInstallDotshRouteImport.update({
  id: '/cli/install.sh',
  path: '/cli/install.sh',
  getParentRoute: () => rootRouteImport,
} as any)
const CliFileshareDotshRoute = CliFileshareDotshRouteImport.update({
  id: '/cli/fileshare.sh',
  path: '/cli/fileshare.sh',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadRoute = ApiUploadRouteImport.update({
  id: '/api/upload',
  path: '/api/upload',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedKeysRoute = AuthenticatedKeysRouteImport.update({
  id: '/keys',
  path: '/keys',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiUploadsIndexRoute = ApiUploadsIndexRouteImport.update({
  id: '/api/uploads/',
  path: '/api/uploads/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiFilesSlugRoute = ApiFilesSlugRouteImport.update({
  id: '/api/files/$slug',
  path: '/api/files/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCliConfigRoute = ApiCliConfigRouteImport.update({
  id: '/api/cli/config',
  path: '/api/cli/config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiUploadsIdCompleteRoute = ApiUploadsIdCompleteRouteImport.update({
  id: '/api/uploads/$id/complete',
  path: '/api/uploads/$id/complete',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1QrRoute = ApiPublicV1QrRouteImport.update({
  id: '/api/public/v1/qr',
  path: '/api/public/v1/qr',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicCronCleanupRoute = ApiPublicCronCleanupRouteImport.update({
  id: '/api/public/cron/cleanup',
  path: '/api/public/cron/cleanup',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1UploadsInitRoute = ApiPublicV1UploadsInitRouteImport.update({
  id: '/api/public/v1/uploads/init',
  path: '/api/public/v1/uploads/init',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1MeKeysRoute = ApiPublicV1MeKeysRouteImport.update({
  id: '/api/public/v1/me/keys',
  path: '/api/public/v1/me/keys',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1MeDropsRoute = ApiPublicV1MeDropsRouteImport.update({
  id: '/api/public/v1/me/drops',
  path: '/api/public/v1/me/drops',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1DropsSlugRoute = ApiPublicV1DropsSlugRouteImport.update({
  id: '/api/public/v1/drops/$slug',
  path: '/api/public/v1/drops/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1ClaimsCodeRoute = ApiPublicV1ClaimsCodeRouteImport.update({
  id: '/api/public/v1/claims/$code',
  path: '/api/public/v1/claims/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicV1UploadsIdCompleteRoute =
  ApiPublicV1UploadsIdCompleteRouteImport.update({
    id: '/api/public/v1/uploads/$id/complete',
    path: '/api/public/v1/uploads/$id/complete',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicV1MeKeysIdRoute = ApiPublicV1MeKeysIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => ApiPublicV1MeKeysRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/receive': typeof ReceiveRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/keys': typeof AuthenticatedKeysRoute
  '/api/upload': typeof ApiUploadRoute
  '/cli/fileshare.sh': typeof CliFileshareDotshRoute
  '/cli/install.sh': typeof CliInstallDotshRoute
  '/d/$slug': typeof DSlugRoute
  '/docs/api': typeof DocsApiRoute
  '/docs/cli': typeof DocsCliRoute
  '/docs/': typeof DocsIndexRoute
  '/api/cli/config': typeof ApiCliConfigRoute
  '/api/files/$slug': typeof ApiFilesSlugRoute
  '/api/uploads/': typeof ApiUploadsIndexRoute
  '/api/public/cron/cleanup': typeof ApiPublicCronCleanupRoute
  '/api/public/v1/qr': typeof ApiPublicV1QrRoute
  '/api/uploads/$id/complete': typeof ApiUploadsIdCompleteRoute
  '/api/public/v1/claims/$code': typeof ApiPublicV1ClaimsCodeRoute
  '/api/public/v1/drops/$slug': typeof ApiPublicV1DropsSlugRoute
  '/api/public/v1/me/drops': typeof ApiPublicV1MeDropsRoute
  '/api/public/v1/me/keys': typeof ApiPublicV1MeKeysRouteWithChildren
  '/api/public/v1/uploads/init': typeof ApiPublicV1UploadsInitRoute
  '/api/public/v1/me/keys/$id': typeof ApiPublicV1MeKeysIdRoute
  '/api/public/v1/uploads/$id/complete': typeof ApiPublicV1UploadsIdCompleteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/receive': typeof ReceiveRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/keys': typeof AuthenticatedKeysRoute
  '/api/upload': typeof ApiUploadRoute
  '/cli/fileshare.sh': typeof CliFileshareDotshRoute
  '/cli/install.sh': typeof CliInstallDotshRoute
  '/d/$slug': typeof DSlugRoute
  '/docs/api': typeof DocsApiRoute
  '/docs/cli': typeof DocsCliRoute
  '/docs': typeof DocsIndexRoute
  '/api/cli/config': typeof ApiCliConfigRoute
  '/api/files/$slug': typeof ApiFilesSlugRoute
  '/api/uploads': typeof ApiUploadsIndexRoute
  '/api/public/cron/cleanup': typeof ApiPublicCronCleanupRoute
  '/api/public/v1/qr': typeof ApiPublicV1QrRoute
  '/api/uploads/$id/complete': typeof ApiUploadsIdCompleteRoute
  '/api/public/v1/claims/$code': typeof ApiPublicV1ClaimsCodeRoute
  '/api/public/v1/drops/$slug': typeof ApiPublicV1DropsSlugRoute
  '/api/public/v1/me/drops': typeof ApiPublicV1MeDropsRoute
  '/api/public/v1/me/keys': typeof ApiPublicV1MeKeysRouteWithChildren
  '/api/public/v1/uploads/init': typeof ApiPublicV1UploadsInitRoute
  '/api/public/v1/me/keys/$id': typeof ApiPublicV1MeKeysIdRoute
  '/api/public/v1/uploads/$id/complete': typeof ApiPublicV1UploadsIdCompleteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/receive': typeof ReceiveRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/keys': typeof AuthenticatedKeysRoute
  '/api/upload': typeof ApiUploadRoute
  '/cli/fileshare.sh': typeof CliFileshareDotshRoute
  '/cli/install.sh': typeof CliInstallDotshRoute
  '/d/$slug': typeof DSlugRoute
  '/docs/api': typeof DocsApiRoute
  '/docs/cli': typeof DocsCliRoute
  '/docs/': typeof DocsIndexRoute
  '/api/cli/config': typeof ApiCliConfigRoute
  '/api/files/$slug': typeof ApiFilesSlugRoute
  '/api/uploads/': typeof ApiUploadsIndexRoute
  '/api/public/cron/cleanup': typeof ApiPublicCronCleanupRoute
  '/api/public/v1/qr': typeof ApiPublicV1QrRoute
  '/api/uploads/$id/complete': typeof ApiUploadsIdCompleteRoute
  '/api/public/v1/claims/$code': typeof ApiPublicV1ClaimsCodeRoute
  '/api/public/v1/drops/$slug': typeof ApiPublicV1DropsSlugRoute
  '/api/public/v1/me/drops': typeof ApiPublicV1MeDropsRoute
  '/api/public/v1/me/keys': typeof ApiPublicV1MeKeysRouteWithChildren
  '/api/public/v1/uploads/init': typeof ApiPublicV1UploadsInitRoute
  '/api/public/v1/me/keys/$id': typeof ApiPublicV1MeKeysIdRoute
  '/api/public/v1/uploads/$id/complete': typeof ApiPublicV1UploadsIdCompleteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/receive'
    | '/dashboard'
    | '/keys'
    | '/api/upload'
    | '/cli/fileshare.sh'
    | '/cli/install.sh'
    | '/d/$slug'
    | '/docs/api'
    | '/docs/cli'
    | '/docs/'
    | '/api/cli/config'
    | '/api/files/$slug'
    | '/api/uploads/'
    | '/api/public/cron/cleanup'
    | '/api/public/v1/qr'
    | '/api/uploads/$id/complete'
    | '/api/public/v1/claims/$code'
    | '/api/public/v1/drops/$slug'
    | '/api/public/v1/me/drops'
    | '/api/public/v1/me/keys'
    | '/api/public/v1/uploads/init'
    | '/api/public/v1/me/keys/$id'
    | '/api/public/v1/uploads/$id/complete'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/receive'
    | '/dashboard'
    | '/keys'
    | '/api/upload'
    | '/cli/fileshare.sh'
    | '/cli/install.sh'
    | '/d/$slug'
    | '/docs/api'
    | '/docs/cli'
    | '/docs'
    | '/api/cli/config'
    | '/api/files/$slug'
    | '/api/uploads'
    | '/api/public/cron/cleanup'
    | '/api/public/v1/qr'
    | '/api/uploads/$id/complete'
    | '/api/public/v1/claims/$code'
    | '/api/public/v1/drops/$slug'
    | '/api/public/v1/me/drops'
    | '/api/public/v1/me/keys'
    | '/api/public/v1/uploads/init'
    | '/api/public/v1/me/keys/$id'
    | '/api/public/v1/uploads/$id/complete'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/receive'
    | '/_authenticated/dashboard'
    | '/_authenticated/keys'
    | '/api/upload'
    | '/cli/fileshare.sh'
    | '/cli/install.sh'
    | '/d/$slug'
    | '/docs/api'
    | '/docs/cli'
    | '/docs/'
    | '/api/cli/config'
    | '/api/files/$slug'
    | '/api/uploads/'
    | '/api/public/cron/cleanup'
    | '/api/public/v1/qr'
    | '/api/uploads/$id/complete'
    | '/api/public/v1/claims/$code'
    | '/api/public/v1/drops/$slug'
    | '/api/public/v1/me/drops'
    | '/api/public/v1/me/keys'
    | '/api/public/v1/uploads/init'
    | '/api/public/v1/me/keys/$id'
    | '/api/public/v1/uploads/$id/complete'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ReceiveRoute: typeof ReceiveRoute
  ApiUploadRoute: typeof ApiUploadRoute
  CliFileshareDotshRoute: typeof CliFileshareDotshRoute
  CliInstallDotshRoute: typeof CliInstallDotshRoute
  DSlugRoute: typeof DSlugRoute
  DocsApiRoute: typeof DocsApiRoute
  DocsCliRoute: typeof DocsCliRoute
  DocsIndexRoute: typeof DocsIndexRoute
  ApiCliConfigRoute: typeof ApiCliConfigRoute
  ApiFilesSlugRoute: typeof ApiFilesSlugRoute
  ApiUploadsIndexRoute: typeof ApiUploadsIndexRoute
  ApiPublicCronCleanupRoute: typeof ApiPublicCronCleanupRoute
  ApiPublicV1QrRoute: typeof ApiPublicV1QrRoute
  ApiUploadsIdCompleteRoute: typeof ApiUploadsIdCompleteRoute
  ApiPublicV1ClaimsCodeRoute: typeof ApiPublicV1ClaimsCodeRoute
  ApiPublicV1DropsSlugRoute: typeof ApiPublicV1DropsSlugRoute
  ApiPublicV1MeDropsRoute: typeof ApiPublicV1MeDropsRoute
  ApiPublicV1MeKeysRoute: typeof ApiPublicV1MeKeysRouteWithChildren
  ApiPublicV1UploadsInitRoute: typeof ApiPublicV1UploadsInitRoute
  ApiPublicV1UploadsIdCompleteRoute: typeof ApiPublicV1UploadsIdCompleteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/receive': {
      id: '/receive'
      path: '/receive'
      fullPath: '/receive'
      preLoaderRoute: typeof ReceiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/': {
      id: '/docs/'
      path: '/docs'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/cli': {
      id: '/docs/cli'
      path: '/docs/cli'
      fullPath: '/docs/cli'
      preLoaderRoute: typeof DocsCliRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/docs/api': {
      id: '/docs/api'
      path: '/docs/api'
      fullPath: '/docs/api'
      preLoaderRoute: typeof DocsApiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/d/$slug': {
      id: '/d/$slug'
      path: '/d/$slug'
      fullPath: '/d/$slug'
      preLoaderRoute: typeof DSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cli/install.sh': {
      id: '/cli/install.sh'
      path: '/cli/install.sh'
      fullPath: '/cli/install.sh'
      preLoaderRoute: typeof CliInstallDotshRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cli/fileshare.sh': {
      id: '/cli/fileshare.sh'
      path: '/cli/fileshare.sh'
      fullPath: '/cli/fileshare.sh'
      preLoaderRoute: typeof CliFileshareDotshRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/upload': {
      id: '/api/upload'
      path: '/api/upload'
      fullPath: '/api/upload'
      preLoaderRoute: typeof ApiUploadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/keys': {
      id: '/_authenticated/keys'
      path: '/keys'
      fullPath: '/keys'
      preLoaderRoute: typeof AuthenticatedKeysRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/uploads/': {
      id: '/api/uploads/'
      path: '/api/uploads'
      fullPath: '/api/uploads/'
      preLoaderRoute: typeof ApiUploadsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/files/$slug': {
      id: '/api/files/$slug'
      path: '/api/files/$slug'
      fullPath: '/api/files/$slug'
      preLoaderRoute: typeof ApiFilesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cli/config': {
      id: '/api/cli/config'
      path: '/api/cli/config'
      fullPath: '/api/cli/config'
      preLoaderRoute: typeof ApiCliConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/uploads/$id/complete': {
      id: '/api/uploads/$id/complete'
      path: '/api/uploads/$id/complete'
      fullPath: '/api/uploads/$id/complete'
      preLoaderRoute: typeof ApiUploadsIdCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/qr': {
      id: '/api/public/v1/qr'
      path: '/api/public/v1/qr'
      fullPath: '/api/public/v1/qr'
      preLoaderRoute: typeof ApiPublicV1QrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/cleanup': {
      id: '/api/public/cron/cleanup'
      path: '/api/public/cron/cleanup'
      fullPath: '/api/public/cron/cleanup'
      preLoaderRoute: typeof ApiPublicCronCleanupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/uploads/init': {
      id: '/api/public/v1/uploads/init'
      path: '/api/public/v1/uploads/init'
      fullPath: '/api/public/v1/uploads/init'
      preLoaderRoute: typeof ApiPublicV1UploadsInitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/me/keys': {
      id: '/api/public/v1/me/keys'
      path: '/api/public/v1/me/keys'
      fullPath: '/api/public/v1/me/keys'
      preLoaderRoute: typeof ApiPublicV1MeKeysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/me/drops': {
      id: '/api/public/v1/me/drops'
      path: '/api/public/v1/me/drops'
      fullPath: '/api/public/v1/me/drops'
      preLoaderRoute: typeof ApiPublicV1MeDropsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/drops/$slug': {
      id: '/api/public/v1/drops/$slug'
      path: '/api/public/v1/drops/$slug'
      fullPath: '/api/public/v1/drops/$slug'
      preLoaderRoute: typeof ApiPublicV1DropsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/claims/$code': {
      id: '/api/public/v1/claims/$code'
      path: '/api/public/v1/claims/$code'
      fullPath: '/api/public/v1/claims/$code'
      preLoaderRoute: typeof ApiPublicV1ClaimsCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/uploads/$id/complete': {
      id: '/api/public/v1/uploads/$id/complete'
      path: '/api/public/v1/uploads/$id/complete'
      fullPath: '/api/public/v1/uploads/$id/complete'
      preLoaderRoute: typeof ApiPublicV1UploadsIdCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/v1/me/keys/$id': {
      id: '/api/public/v1/me/keys/$id'
      path: '/$id'
      fullPath: '/api/public/v1/me/keys/$id'
      preLoaderRoute: typeof ApiPublicV1MeKeysIdRouteImport
      parentRoute: typeof ApiPublicV1MeKeysRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedKeysRoute: typeof AuthenticatedKeysRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedKeysRoute: AuthenticatedKeysRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ApiPublicV1MeKeysRouteChildren {
  ApiPublicV1MeKeysIdRoute: typeof ApiPublicV1MeKeysIdRoute
}

const ApiPublicV1MeKeysRouteChildren: ApiPublicV1MeKeysRouteChildren = {
  ApiPublicV1MeKeysIdRoute: ApiPublicV1MeKeysIdRoute,
}

const ApiPublicV1MeKeysRouteWithChildren =
  ApiPublicV1MeKeysRoute._addFileChildren(ApiPublicV1MeKeysRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ReceiveRoute: ReceiveRoute,
  ApiUploadRoute: ApiUploadRoute,
  CliFileshareDotshRoute: CliFileshareDotshRoute,
  CliInstallDotshRoute: CliInstallDotshRoute,
  DSlugRoute: DSlugRoute,
  DocsApiRoute: DocsApiRoute,
  DocsCliRoute: DocsCliRoute,
  DocsIndexRoute: DocsIndexRoute,
  ApiCliConfigRoute: ApiCliConfigRoute,
  ApiFilesSlugRoute: ApiFilesSlugRoute,
  ApiUploadsIndexRoute: ApiUploadsIndexRoute,
  ApiPublicCronCleanupRoute: ApiPublicCronCleanupRoute,
  ApiPublicV1QrRoute: ApiPublicV1QrRoute,
  ApiUploadsIdCompleteRoute: ApiUploadsIdCompleteRoute,
  ApiPublicV1ClaimsCodeRoute: ApiPublicV1ClaimsCodeRoute,
  ApiPublicV1DropsSlugRoute: ApiPublicV1DropsSlugRoute,
  ApiPublicV1MeDropsRoute: ApiPublicV1MeDropsRoute,
  ApiPublicV1MeKeysRoute: ApiPublicV1MeKeysRouteWithChildren,
  ApiPublicV1UploadsInitRoute: ApiPublicV1UploadsInitRoute,
  ApiPublicV1UploadsIdCompleteRoute: ApiPublicV1UploadsIdCompleteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
